services:
  web:
    container_name: portfolio_web
    build: .
    ports:
      - "8001:5000"
    stop_signal: SIGINT

  nginx:
    container_name: portfolio_nginx
    image: nginx:1.29.0
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./templates:/etc/nginx/templates
    ports:
      - "8000:80"
    depends_on:
      - web