volumes:
  db_data:

services:
  db:
    container_name: portfolio_db
    image: postgres:17.5
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    # restart: always
    ports:
      - "5432:5432"

  web:
    container_name: portfolio_web
    build: .
    ports:
      - "5000:5000"
    stop_signal: SIGINT
    volumes:
      - .:/app
      - ./portfolio_app/templates:/app/portfolio_app/templates
      - ./portfolio_app/static:/app/portfolio_app/static
      - ./media_data:/app/media_data
    depends_on:
      - db

  nginx:
    container_name: portfolio_nginx
    image: nginx:1.29.0
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"
    depends_on:
      - web