services:
  web:
    container_name: portfolio_web
    build: .
    ports:
      - "5000:5000"
    stop_signal: SIGINT
    volumes:
      - .:/app
      - ./templates:/app/templates
      - ./static:/app/static

  nginx:
    container_name: portfolio_nginx
    image: nginx:1.29.0
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"
    depends_on:
      - web