FROM python:3.13-slim

WORKDIR /app

# Install psycopg2 dependencies
RUN apt-get update && apt-get install -y libpq-dev gcc

COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir

RUN pip install pytest-cov pytest-html pytest-xdist

COPY . .

RUN mkdir -p /app/test_media_data

CMD ["pytest"]
