"""Fix User model

Revision ID: 0d77044fdc38
Revises: f38923e0d6a5
Create Date: 2025-07-19 07:48:58.481679

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0d77044fdc38'
down_revision = 'f38923e0d6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('is_admin', sa.Boolean(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
