"""Add column to Projects

Revision ID: 4d34649a37b6
Revises: a42308edfa7e
Create Date: 2025-07-27 03:01:09.867657

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4d34649a37b6'
down_revision = 'a42308edfa7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stack', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('tasks', sa.Text(), nullable=False))
        batch_op.alter_column(
            'img_path', existing_type=sa.VARCHAR(length=120), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column(
            'img_path', existing_type=sa.VARCHAR(length=120), nullable=False
        )
        batch_op.drop_column('tasks')
        batch_op.drop_column('stack')

    # ### end Alembic commands ###
