"""Remove image

Revision ID: a42308edfa7e
Revises: cd140ac6c6da
Create Date: 2025-07-26 07:03:14.499466

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a42308edfa7e'
down_revision = 'cd140ac6c6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'image',
                sa.VARCHAR(length=80),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
