"""Add img_path

Revision ID: cd140ac6c6da
Revises: 0d77044fdc38
Create Date: 2025-07-26 06:14:12.029836

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cd140ac6c6da'
down_revision = '0d77044fdc38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('img_path', sa.String(length=120), nullable=False)
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('img_path', sa.String(length=120), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('img_path')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('img_path')

    # ### end Alembic commands ###
