"""Add project model

Revision ID: d631e84ce69d
Revises: ef10a9fc0ef5
Create Date: 2025-07-19 05:24:58.402434

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd631e84ce69d'
down_revision = 'ef10a9fc0ef5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=80), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('image', sa.String(length=80), nullable=False),
        sa.Column('role', sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('title'),
    )
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password', sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username'),
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            'username',
            sa.VARCHAR(length=80),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
        sa.UniqueConstraint(
            'username',
            name=op.f('user_username_key'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table('users')
    op.drop_table('projects')
    # ### end Alembic commands ###
