"""Add flask login

Revision ID: f38923e0d6a5
Revises: d631e84ce69d
Create Date: 2025-07-19 06:02:45.280399

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f38923e0d6a5'
down_revision = 'd631e84ce69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('email', sa.String(length=120), nullable=False)
        )
        batch_op.add_column(
            sa.Column('password_hash', sa.String(length=255), nullable=False)
        )
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'password',
                sa.VARCHAR(length=80),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
